
TYPE
	ConvStepEnum : 
		(
		C_WAIT_ENABLE,
		C_ENABLE_REGISTER_FB,
		C_WAIT_ENABLE_REGISTER_FB,
		C_ENABLE_REGISTER,
		C_WAIT_ENABLE_REGISTER,
		C_ENABLE_ADD_REGISTER_FBS,
		C_WAIT_ENABLE_ADD_REGISTER_FBS,
		C_WAIT_START_PROCESS,
		C_START_PROCESS,
		C_WAIT_PROCESS_STARTED,
		C_PROCESSING,
		C_ERROR
		);
END_TYPE
