
TYPE
	PlaceStepEnum : 
		(
		P_WAIT_ENABLE,
		P_ENABLE_REGISTER_FB,
		P_WAIT_ENABLE_REGISTER_FB,
		P_ENABLE_REGISTER_COMP,
		P_WAIT_ENABLE_REGISTER_COMP,
		P_ENABLE_ADD_REGISTER_FBS,
		P_WAIT_ENABLE_ADD_REGISTER_FBS,
		P_WAIT_START_PROCESS,
		P_CREATE_OBJECTS,
		P_WAIT_CREATE_OBJECTS,
		P_WAIT_REGISTER_FULL,
		P_DELAY_DELETE,
		P_DELETE_OBJECTS,
		P_WAIT_DELETE_OBJECTS,
		P_DELAY_CREATE,
		P_ERROR
		);
END_TYPE
