
TYPE
	PickCoreStepEnum : 
		(
		PC_WAIT_ENABLE,
		PC_ENABLE_PICK_CORE,
		PC_WAIT_ENABLE_PICK_CORE,
		PC_ENABLE_CORE_PROCESS,
		PC_WAIT_ENABLE_CORE_PROCESS,
		PC_WAIT_START_CORE_PROCESS,
		PC_READY_TO_START,
		PC_STARTED,
		PC_ERROR
		);
END_TYPE
