
TYPE
	RCStepEnum : 
		(
		RC_WAIT_ENABLE,
		RC_POWER_ROBOT,
		RC_HOME_ROBOT,
		RC_ROBOT_READY,
		RC_WAIT_ENABLE_AXIS_FB,
		RC_POWER_AXIS,
		RC_WAIT_POWER_AXIS,
		RC_HOME_AXIS,
		RC_WAIT_HOME_AXIS,
		RC_READY,
		RC_START_PROCESS,
		RC_WAIT_PROCESS_STARTED,
		RC_PROCESSING,
		RC_ERROR, 
		RC_ERROR_STOP
		);
END_TYPE
